import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

async function render(){const workerUrl=new URL("../dist/server/index.js",import.meta.url);workerUrl.searchParams.set("test",`${process.pid}-${Date.now()}`);const {default:worker}=await import(workerUrl.href);return worker.fetch(new Request("http://localhost/",{headers:{accept:"text/html"}}),{ASSETS:{fetch:async()=>new Response("Not found",{status:404})}},{waitUntil(){},passThroughOnException(){}})}

test("renderiza CRC Conecta y sus metadatos",async()=>{const response=await render();assert.equal(response.status,200);assert.match(response.headers.get("content-type")??"",/^text\/html\b/i);const html=await response.text();assert.match(html,/<title>CRC Conecta/);assert.match(html,/Comunidad de Renovación Cristiana/);assert.match(html,/(?:Modo demostración|Preparando sesión segura…)/)});

test("mantiene contratos de sesión y persistencia Supabase",async()=>{const [auth,repository,migration]=await Promise.all([readFile(new URL("../features/auth/AuthProvider.tsx",import.meta.url),"utf8"),readFile(new URL("../features/people/repository.ts",import.meta.url),"utf8"),readFile(new URL("../supabase/migrations/20260829010000_sprint_10_supabase_sessions_crud.sql",import.meta.url),"utf8")]);assert.match(auth,/onAuthStateChange/);assert.match(auth,/signInWithPassword/);assert.match(repository,/from\("people"\)\.insert/);assert.match(repository,/from\("people"\)\.update/);assert.match(repository,/archived_at/);assert.match(migration,/get_my_access_context/);assert.match(migration,/people_document_present_unique/)});

test("expone la configuración pública de Supabase al cliente",async()=>{const config=await readFile(new URL("../lib/supabase/config.ts",import.meta.url),"utf8");assert.match(config,/process\.env\.NEXT_PUBLIC_SUPABASE_URL/);assert.match(config,/process\.env\.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY/);assert.doesNotMatch(config,/process\.env\s*\[/)});

test("persiste la fecha de nacimiento de las personas",async()=>{const [view,repository,validation]=await Promise.all([readFile(new URL("../features/people/PeopleView.tsx",import.meta.url),"utf8"),readFile(new URL("../features/people/repository.ts",import.meta.url),"utf8"),readFile(new URL("../features/people/validation.ts",import.meta.url),"utf8")]);assert.match(view,/Fecha de nacimiento/);assert.match(view,/type="date"/);assert.match(repository,/birth_date:draft\.birthDate/);assert.match(repository,/birth_date/);assert.match(validation,/fecha de nacimiento/)});

test("familias usa CRUD y vínculos reales de Supabase",async()=>{const [view,repository]=await Promise.all([readFile(new URL("../features/families/FamiliesView.tsx",import.meta.url),"utf8"),readFile(new URL("../features/families/repository.ts",import.meta.url),"utf8")]);assert.doesNotMatch(view,/Datos ficticios|Familia Pérez Gómez/);assert.match(repository,/from\("families"\)\.insert/);assert.match(repository,/from\("families"\)\.update/);assert.match(repository,/from\("family_members"\)\.insert/);assert.match(repository,/from\("family_members"\)\.delete/)});

test("valida y persiste documentos CC, TI y RC",async()=>{const [view,repository,validation]=await Promise.all([readFile(new URL("../features/people/PeopleView.tsx",import.meta.url),"utf8"),readFile(new URL("../features/people/repository.ts",import.meta.url),"utf8"),readFile(new URL("../features/people/validation.ts",import.meta.url),"utf8")]);assert.match(view,/CC · Cédula de ciudadanía/);assert.match(view,/TI · Tarjeta de identidad/);assert.match(view,/RC · Registro civil/);assert.match(repository,/document_type:draft\.documentType/);assert.match(repository,/document_number:draft\.documentNumber/);assert.match(validation,/La CC debe contener/);assert.match(validation,/La TI debe contener/);assert.match(validation,/El RC debe contener/)});

test("asistencia usa eventos y registros reales filtrados por sede",async()=>{const [view,repository]=await Promise.all([readFile(new URL("../features/attendance/AttendanceView.tsx",import.meta.url),"utf8"),readFile(new URL("../features/attendance/repository.ts",import.meta.url),"utf8")]);assert.doesNotMatch(view,/María Rodríguez|Culto familiar|Datos ficticios/);assert.match(view,/Asistencia por sede/);assert.match(view,/Grupos de edad presentes/);assert.match(repository,/from\("events"\)\.select/);assert.match(repository,/from\("attendance"\)\.insert/);assert.match(repository,/from\("attendance"\)\.update/);assert.match(repository,/\.eq\("site_id",selectedSiteId\)/)});

test("discipulado conecta personas, formación, grupos y avance real",async()=>{const [view,repository,migration]=await Promise.all([readFile(new URL("../features/groups/GroupsView.tsx",import.meta.url),"utf8"),readFile(new URL("../features/groups/repository.ts",import.meta.url),"utf8"),readFile(new URL("../supabase/migrations/20260901010000_discipleship_teacher_group_management.sql",import.meta.url),"utf8")]);assert.doesNotMatch(view,/Discipulado Grupo 2026-04|María Rodríguez/);assert.match(view,/Alumno externo/);assert.match(view,/Maestro discipulador/);assert.match(repository,/from\("training_programs"\)/);assert.match(repository,/from\("training_groups"\)\.insert/);assert.match(repository,/from\("enrollments"\)\.insert/);assert.match(repository,/from\("class_sessions"\)\.insert/);assert.match(repository,/completed\/total\*100/);assert.match(migration,/DISCIPLESHIP_TEACHER/)});

test("formación persiste programas, módulos y lecciones consumidos por discipulado",async()=>{const [view,repository]=await Promise.all([readFile(new URL("../features/training/TrainingView.tsx",import.meta.url),"utf8"),readFile(new URL("../features/training/repository.ts",import.meta.url),"utf8")]);assert.doesNotMatch(view,/Un nuevo nacimiento y una nueva vida|seedPrograms/);assert.match(view,/Biblioteca privada/);assert.match(repository,/from\("training_programs"\)\.insert/);assert.match(repository,/from\("training_modules"\)\.insert/);assert.match(repository,/from\("lessons"\)\.insert/)});

test("muestra la cuenta activa y un cierre de sesión visible",async()=>{const page=await readFile(new URL("../app/page.tsx",import.meta.url),"utf8");assert.match(page,/Sesión activa/);assert.match(page,/className="logout-button"/);assert.match(page,/Cerrar sesión de/);assert.match(page,/void signOut\(\)/)});

test("Formación 2.0 administra archivos y recursos interactivos",async()=>{const[view,repository,migration]=await Promise.all([readFile(new URL("../features/training/TrainingView.tsx",import.meta.url),"utf8"),readFile(new URL("../features/training/repository.ts",import.meta.url),"utf8"),readFile(new URL("../supabase/migrations/20260902020000_training_content_library.sql",import.meta.url),"utf8")]);assert.match(view,/Arrastra archivos aquí/);assert.match(view,/Enlace o YouTube/);assert.match(view,/ResourcePreview/);assert.match(repository,/storage\.from\(bucket\)\.upload/);assert.match(repository,/createSignedUrl/);assert.match(migration,/lesson_resources/);assert.match(migration,/training-materials/);assert.match(migration,/training\.manage/)});
