import assert from "node:assert/strict";
import { readFile,readdir } from "node:fs/promises";
import test from "node:test";

async function render(path="/"){const workerUrl=new URL("../dist/server/index.js",import.meta.url);workerUrl.searchParams.set("test",`${process.pid}-${Date.now()}`);const {default:worker}=await import(workerUrl.href);return worker.fetch(new Request(`http://localhost${path}`,{headers:{accept:"text/html"}}),{ASSETS:{fetch:async()=>new Response("Not found",{status:404})}},{waitUntil(){},passThroughOnException(){}})}

test("renderiza CRC Conecta y sus metadatos",async()=>{const response=await render();assert.equal(response.status,200);assert.match(response.headers.get("content-type")??"",/^text\/html\b/i);const html=await response.text();assert.match(html,/<title>CRC Conecta/);assert.match(html,/Comunidad de Renovación Cristiana/);assert.match(html,/(?:Modo demostración|Preparando sesión segura…)/)});

test("mantiene contratos de sesión y persistencia Supabase",async()=>{const [auth,repository,migration]=await Promise.all([readFile(new URL("../features/auth/AuthProvider.tsx",import.meta.url),"utf8"),readFile(new URL("../features/people/repository.ts",import.meta.url),"utf8"),readFile(new URL("../supabase/migrations/20260829010000_sprint_10_supabase_sessions_crud.sql",import.meta.url),"utf8")]);assert.match(auth,/onAuthStateChange/);assert.match(auth,/signInWithPassword/);assert.match(repository,/from\("people"\)\.insert/);assert.match(repository,/from\("people"\)\.update/);assert.match(repository,/archived_at/);assert.match(migration,/get_my_access_context/);assert.match(migration,/people_document_present_unique/)});

test("expone la configuración pública de Supabase al cliente",async()=>{const config=await readFile(new URL("../lib/supabase/config.ts",import.meta.url),"utf8");assert.match(config,/process\.env\.NEXT_PUBLIC_SUPABASE_URL/);assert.match(config,/process\.env\.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY/);assert.doesNotMatch(config,/process\.env\s*\[/)});

test("persiste la fecha de nacimiento de las personas",async()=>{const [view,repository,validation]=await Promise.all([readFile(new URL("../features/people/PeopleView.tsx",import.meta.url),"utf8"),readFile(new URL("../features/people/repository.ts",import.meta.url),"utf8"),readFile(new URL("../features/people/validation.ts",import.meta.url),"utf8")]);assert.match(view,/Fecha de nacimiento/);assert.match(view,/type="date"/);assert.match(repository,/birth_date:draft\.birthDate/);assert.match(repository,/birth_date/);assert.match(validation,/fecha de nacimiento/)});

test("familias usa CRUD y vínculos reales de Supabase",async()=>{const [view,repository]=await Promise.all([readFile(new URL("../features/families/FamiliesView.tsx",import.meta.url),"utf8"),readFile(new URL("../features/families/repository.ts",import.meta.url),"utf8")]);assert.doesNotMatch(view,/Datos ficticios|Familia Pérez Gómez/);assert.match(repository,/from\("families"\)\.insert/);assert.match(repository,/from\("families"\)\.update/);assert.match(repository,/from\("family_members"\)\.insert/);assert.match(repository,/from\("family_members"\)\.delete/)});

test("valida y persiste documentos CC, TI y RC",async()=>{const [view,repository,validation]=await Promise.all([readFile(new URL("../features/people/PeopleView.tsx",import.meta.url),"utf8"),readFile(new URL("../features/people/repository.ts",import.meta.url),"utf8"),readFile(new URL("../features/people/validation.ts",import.meta.url),"utf8")]);assert.match(view,/CC · Cédula de ciudadanía/);assert.match(view,/TI · Tarjeta de identidad/);assert.match(view,/RC · Registro civil/);assert.match(repository,/document_type:draft\.documentType/);assert.match(repository,/document_number:draft\.documentNumber/);assert.match(validation,/La CC debe contener/);assert.match(validation,/La TI debe contener/);assert.match(validation,/El RC debe contener/)});

test("asistencia usa eventos y registros reales filtrados por sede",async()=>{const [view,repository]=await Promise.all([readFile(new URL("../features/attendance/AttendanceView.tsx",import.meta.url),"utf8"),readFile(new URL("../features/attendance/repository.ts",import.meta.url),"utf8")]);assert.doesNotMatch(view,/María Rodríguez|Culto familiar|Datos ficticios/);assert.match(view,/Asistencia por sede/);assert.match(view,/Grupos de edad presentes/);assert.match(repository,/from\("events"\)\.select/);assert.match(repository,/from\("attendance"\)\.insert/);assert.match(repository,/from\("attendance"\)\.update/);assert.match(repository,/\.eq\("site_id",selectedSiteId\)/)});

test("discipulado conecta personas, formación, grupos y avance real",async()=>{const [view,repository,migration]=await Promise.all([readFile(new URL("../features/groups/GroupsView.tsx",import.meta.url),"utf8"),readFile(new URL("../features/groups/repository.ts",import.meta.url),"utf8"),readFile(new URL("../supabase/migrations/20260901010000_discipleship_teacher_group_management.sql",import.meta.url),"utf8")]);assert.doesNotMatch(view,/Discipulado Grupo 2026-04|María Rodríguez/);assert.match(view,/Alumno externo/);assert.match(view,/Maestro discipulador/);assert.match(repository,/from\("training_programs"\)/);assert.match(repository,/from\("training_groups"\)\.insert/);assert.match(repository,/from\("enrollments"\)\.insert/);assert.match(repository,/from\("class_sessions"\)\.insert/);assert.match(repository,/completed\/total\*100/);assert.match(migration,/DISCIPLESHIP_TEACHER/)});

test("formación persiste programas, módulos y lecciones consumidos por discipulado",async()=>{const [view,repository]=await Promise.all([readFile(new URL("../features/training/TrainingView.tsx",import.meta.url),"utf8"),readFile(new URL("../features/training/repository.ts",import.meta.url),"utf8")]);assert.doesNotMatch(view,/Un nuevo nacimiento y una nueva vida|seedPrograms/);assert.match(view,/Biblioteca privada/);assert.match(repository,/from\("training_programs"\)\.insert/);assert.match(repository,/from\("training_modules"\)\.insert/);assert.match(repository,/from\("lessons"\)\.insert/)});

test("mantiene visible el cambio de usuario",async()=>{const page=await readFile(new URL("../app/page.tsx",import.meta.url),"utf8");assert.match(page,/Sesión activa/);assert.match(page,/className="logout-button"/);assert.match(page,/Cambiar usuario/);assert.match(page,/cerrar sesión de/);assert.match(page,/void signOut\(\)/)});

test("el artefacto cliente conserva la conexión pública de Supabase",async()=>{const root=new URL("../dist/client/",import.meta.url);const files=await readdir(root,{recursive:true});const scripts=files.filter(file=>file.endsWith(".js"));const contents=await Promise.all(scripts.map(file=>readFile(new URL(file.replaceAll("\\","/"),root),"utf8")));assert.ok(contents.some(content=>content.includes("zzxicsaqslzyewvslvfd.supabase.co")),"La compilación cliente perdió NEXT_PUBLIC_SUPABASE_URL")});

test("Formación 2.0 administra archivos y recursos interactivos",async()=>{const[view,repository,migration]=await Promise.all([readFile(new URL("../features/training/TrainingView.tsx",import.meta.url),"utf8"),readFile(new URL("../features/training/repository.ts",import.meta.url),"utf8"),readFile(new URL("../supabase/migrations/20260902020000_training_content_library.sql",import.meta.url),"utf8")]);assert.match(view,/Arrastra archivos aquí/);assert.match(view,/Video de YouTube/);assert.match(view,/ResourcePreview/);assert.match(repository,/storage\.from\(bucket\)\.upload/);assert.match(repository,/createSignedUrl/);assert.match(migration,/lesson_resources/);assert.match(migration,/training-materials/);assert.match(migration,/training\.manage/)});

test("Formación 2.0 incrusta únicamente proveedores externos permitidos",async()=>{const[view,repository,migration]=await Promise.all([readFile(new URL("../features/training/TrainingView.tsx",import.meta.url),"utf8"),readFile(new URL("../features/training/repository.ts",import.meta.url),"utf8"),readFile(new URL("../supabase/migrations/20260902030000_training_safe_embeds.sql",import.meta.url),"utf8")]);assert.match(view,/function safeEmbed/);assert.match(view,/prezi\.com/);assert.match(view,/Contenido incrustado/);assert.match(view,/Solo se conservará la URL segura/);assert.match(repository,/embed_provider/);assert.match(migration,/PREZI.*VIMEO.*GOOGLE_SLIDES.*POWERPOINT.*GENIALLY.*CANVA/)});

test("Formación limita la edición a perfiles con training.manage",async()=>{const[view,repository,migration]=await Promise.all([readFile(new URL("../features/training/TrainingView.tsx",import.meta.url),"utf8"),readFile(new URL("../features/training/repository.ts",import.meta.url),"utf8"),readFile(new URL("../supabase/migrations/20260827030000_sprint_5_training_programs_modules_lessons.sql",import.meta.url),"utf8")]);assert.match(view,/Modo consulta/);assert.match(view,/Editar programa/);assert.match(view,/Editar módulo/);assert.match(view,/Editar lección/);assert.match(repository,/current_user_has_org_permission/);assert.match(repository,/training\.manage/);assert.match(repository,/from\("training_programs"\)\.update/);assert.match(repository,/from\("training_modules"\)\.update/);assert.match(repository,/from\("lessons"\)\.update/);assert.match(repository,/from\("lesson_resources"\)\.update/);assert.match(migration,/SUPER_ADMIN.*training\.manage/s);assert.match(migration,/DISCIPLESHIP_COORDINATOR.*training\.manage/s)});

test("Inicio usa datos reales por perfil y sede",async()=>{const[page,view,repository,migration]=await Promise.all([readFile(new URL("../app/page.tsx",import.meta.url),"utf8"),readFile(new URL("../features/dashboard/DashboardView.tsx",import.meta.url),"utf8"),readFile(new URL("../features/dashboard/repository.ts",import.meta.url),"utf8"),readFile(new URL("../supabase/migrations/20260904010000_profile_aware_dashboard.sql",import.meta.url),"utf8")]);assert.match(page,/DashboardView/);assert.match(page,/activeSiteName/);assert.match(view,/INICIO SEGÚN TU PERFIL/);assert.match(view,/Mi avance/);assert.match(view,/Mis grupos/);assert.match(view,/Actividad de la sede/);assert.match(view,/actions\.filter\(item=>item\.show\)/);assert.match(repository,/get_my_dashboard/);assert.match(migration,/security definer/);assert.match(migration,/my_person_id/);assert.match(migration,/target_site_id/);assert.match(migration,/SUPER_ADMIN.*NATIONAL_PASTOR.*SITE_PASTOR.*SITE_ADMIN/s)});

test("persona nueva con Google completa el autoregistro",async()=>{const[auth,view,repository,migration]=await Promise.all([readFile(new URL("../features/auth/AuthProvider.tsx",import.meta.url),"utf8"),readFile(new URL("../features/registration/RegistrationView.tsx",import.meta.url),"utf8"),readFile(new URL("../features/registration/repository.ts",import.meta.url),"utf8"),readFile(new URL("../supabase/migrations/20260905020000_public_self_registration.sql",import.meta.url),"utf8")]);assert.match(auth,/signInWithOAuth/);assert.match(auth,/provider:"google"/);assert.match(view,/Continuar con Google/);assert.match(view,/DATOS PERSONALES/);assert.match(repository,/complete_self_registration/);assert.match(migration,/insert into public\.people/);assert.match(migration,/'CREATED'/)});
test("correo ya registrado no crea duplicados",async()=>{const migration=await readFile(new URL("../supabase/migrations/20260905020000_public_self_registration.sql",import.meta.url),"utf8");assert.match(migration,/lower\(trim\(p\.email\)\)=current_email/);assert.match(migration,/ALREADY_REGISTERED/);assert.match(migration,/Este correo ya está registrado/)});
test("documento ya registrado no crea duplicados",async()=>{const migration=await readFile(new URL("../supabase/migrations/20260905020000_public_self_registration.sql",import.meta.url),"utf8");assert.match(migration,/regexp_replace\(trim\(p\.document_number\)/);assert.match(migration,/VERIFICATION_REQUIRED/);assert.match(migration,/document_person/)});
test("persona existente sin usuario se vincula con identidad verificada",async()=>{const migration=await readFile(new URL("../supabase/migrations/20260905020000_public_self_registration.sql",import.meta.url),"utf8");assert.match(migration,/linked_person_id:=coalesce\(document_person\.id,email_person\.id\)/);assert.match(migration,/update public\.user_accounts set person_id=linked_person_id/);assert.match(migration,/'LINKED'/)});
test("autoregistro no puede asignarse roles privilegiados",async()=>{const migration=await readFile(new URL("../supabase/migrations/20260905020000_public_self_registration.sql",import.meta.url),"utf8");assert.doesNotMatch(migration,/insert into public\.user_roles/i);assert.match(migration,/Nunca asigna roles, permisos, ministerios/)});
test("usuario autoregistrado solo consulta su propia persona",async()=>{const migration=await readFile(new URL("../supabase/migrations/20260905020000_public_self_registration.sql",import.meta.url),"utf8");assert.match(migration,/people_select_own_profile/);assert.match(migration,/ua\.id=auth\.uid\(\) and ua\.person_id=people\.id/);assert.doesNotMatch(migration,/people_update_own_profile/)});
test("usuario existente recibe acceso al Campus sin duplicación",async()=>{const[view,migration]=await Promise.all([readFile(new URL("../features/registration/RegistrationView.tsx",import.meta.url),"utf8"),readFile(new URL("../supabase/migrations/20260905020000_public_self_registration.sql",import.meta.url),"utf8")]);assert.match(migration,/ALREADY_REGISTERED/);assert.match(view,/Ir a Campus CRC/);assert.match(view,/Recuperar acceso/)});
test("la callback OAuth puede abrir la ruta real de registro",async()=>{const response=await render("/registro#access_token=prueba");assert.equal(response.status,200);const html=await response.text();assert.match(html,/Únete a CRC|Comienza tu registro/)});
test("recuperación dirige a una pantalla para definir la nueva contraseña",async()=>{const[auth,response]=await Promise.all([readFile(new URL("../features/auth/AuthProvider.tsx",import.meta.url),"utf8"),render("/recuperar-acceso#access_token=prueba&type=recovery")]);assert.match(auth,/redirectTo:`\$\{window\.location\.origin\}\/recuperar-acceso`/);assert.match(auth,/auth\.updateUser\(\{password\}\)/);assert.equal(response.status,200);const html=await response.text();assert.match(html,/Crea una contraseña nueva/)});
test("nuevo autoregistro queda pendiente de aprobación",async()=>{const[migration,repository,view]=await Promise.all([readFile(new URL("../supabase/migrations/20260906010000_campus_access_approval.sql",import.meta.url),"utf8"),readFile(new URL("../features/registration/repository.ts",import.meta.url),"utf8"),readFile(new URL("../features/registration/RegistrationView.tsx",import.meta.url),"utf8")]);assert.match(migration,/access_status.*PENDING_APPROVAL/);assert.match(migration,/ACCESS_REQUEST_CREATED/);assert.match(repository,/status:"PENDING_APPROVAL"/);assert.match(view,/Registro recibido/);assert.match(view,/result\.status!=="PENDING_APPROVAL"&&<button/)});
test("usuario pendiente no obtiene Campus y recibe mensaje amigable",async()=>{const[page,campus]=await Promise.all([readFile(new URL("../app/page.tsx",import.meta.url),"utf8"),readFile(new URL("../features/campus/CampusView.tsx",import.meta.url),"utf8")]);assert.match(page,/portal\.status!=="ACTIVE"/);assert.match(campus,/Solicitud pendiente de aprobación/);assert.match(campus,/Continuar en el sitio público/)});
test("pastor de otra sede no puede aprobar y pastor de la sede sí",async()=>{const migration=await readFile(new URL("../supabase/migrations/20260906010000_campus_access_approval.sql",import.meta.url),"utf8");assert.match(migration,/current_user_has_permission\('access_requests\.review',request_row\.organization_id,request_row\.site_id\)/);assert.match(migration,/\('SITE_PASTOR','access_requests\.review'\)/);assert.match(migration,/ACCESS_DENIED/)});
test("superadministrador puede revisar solicitudes",async()=>{const migration=await readFile(new URL("../supabase/migrations/20260906010000_campus_access_approval.sql",import.meta.url),"utf8");assert.match(migration,/\('SUPER_ADMIN','access_requests\.review'\)/);assert.match(migration,/review_access_request/)});
test("aprobación activa Campus sin asignar roles",async()=>{const[migration,campus]=await Promise.all([readFile(new URL("../supabase/migrations/20260906010000_campus_access_approval.sql",import.meta.url),"utf8"),readFile(new URL("../features/campus/CampusView.tsx",import.meta.url),"utf8")]);assert.match(migration,/when 'APPROVE' then 'ACTIVE'/);assert.doesNotMatch(migration,/review_access_request[\s\S]*insert into public\.user_roles/);assert.match(campus,/EXPERIENCIA PERSONAL/)});
test("usuario básico no recibe módulos administrativos",async()=>{const page=await readFile(new URL("../app/page.tsx",import.meta.url),"utf8");assert.match(page,/if\(!isAdministrative\)return <CampusView/);assert.match(page,/visibleNav=nav\.filter/);assert.match(page,/effective\.has\(item\.permission\)/)});
test("ruta administrativa directa exige permiso",async()=>{const[page,response]=await Promise.all([readFile(new URL("../app/page.tsx",import.meta.url),"utf8"),render("/admin/personas")]);assert.equal(response.status,200);assert.match(page,/pathname\.startsWith\("\/admin"\)&&!isAdministrative/);assert.match(page,/AccessDeniedView/)});
test("RLS impide a un básico consultar otras personas",async()=>{const migration=await readFile(new URL("../supabase/migrations/20260906010000_campus_access_approval.sql",import.meta.url),"utf8");assert.match(migration,/people_select_own_profile/);assert.match(migration,/ua\.id=auth\.uid\(\) and ua\.person_id=people\.id/);assert.match(migration,/current_user_access_status\(\)='ACTIVE'/)});
test("menú aparece y desaparece con permisos efectivos",async()=>{const page=await readFile(new URL("../app/page.tsx",import.meta.url),"utf8");assert.match(page,/permission:"attendance\.register"/);assert.match(page,/effective\.has\(item\.permission\)/);assert.doesNotMatch(page,/visibleNav=.*role/)});
test("usuario no puede elevar sus propios privilegios",async()=>{const migration=await readFile(new URL("../supabase/migrations/20260906010000_campus_access_approval.sql",import.meta.url),"utf8");assert.match(migration,/SELF_PRIVILEGE_ESCALATION_DENIED/);assert.match(migration,/CANNOT_GRANT_SUPERIOR_PERMISSION/);assert.match(migration,/user_roles_prevent_elevation/)});
test("decisiones y permisos sensibles quedan auditados",async()=>{const migration=await readFile(new URL("../supabase/migrations/20260906010000_campus_access_approval.sql",import.meta.url),"utf8");for(const event of["ACCESS_REQUEST_CREATED","CAMPUS_ACCESS_APPROVED","CAMPUS_ACCESS_REJECTED","CAMPUS_ACCESS_SUSPENDED","ROLE_ASSIGNED","ROLE_REMOVED","PERMISSION_GRANTED","PERMISSION_REVOKED"])assert.match(migration,new RegExp(event));assert.match(migration,/email_delivery_queue/);assert.match(migration,/user_notifications/)});

const agendaFiles=async()=>Promise.all([readFile(new URL("../features/agenda/AgendaCarousel.tsx",import.meta.url),"utf8"),readFile(new URL("../features/agenda/repository.ts",import.meta.url),"utf8"),readFile(new URL("../supabase/migrations/20260907010000_authorized_event_agenda.sql",import.meta.url),"utf8"),readFile(new URL("../app/globals.css",import.meta.url),"utf8"),readFile(new URL("../features/dashboard/DashboardView.tsx",import.meta.url),"utf8")]);
test("superadministrador ve agenda nacional autorizada",async()=>{const[,,migration]=await agendaFiles();assert.match(migration,/r\.code='SUPER_ADMIN'/);assert.match(migration,/ur\.organization_id=e\.organization_id/)});
test("pastor nacional ve sedes autorizadas salvo eventos restringidos",async()=>{const[,,migration]=await agendaFiles();assert.match(migration,/r\.code='NATIONAL_PASTOR'/);assert.match(migration,/not e\.is_restricted/);assert.match(migration,/scope_type='ORGANIZATION'/)});
test("pastor de sede ve su sede y eventos nacionales",async()=>{const[,,migration]=await agendaFiles();assert.match(migration,/r\.code='SITE_PASTOR'/);assert.match(migration,/ur\.site_id=e\.site_id/);assert.match(migration,/ALL_CRC','NATIONAL/)});
test("líder de ministerio recibe eventos por unión de ministerios",async()=>{const[,,migration]=await agendaFiles();assert.match(migration,/audience_type='MINISTRY'/);assert.match(migration,/person_ministries pm/);assert.match(migration,/pm\.ministry_id=ea\.ministry_id/)});
test("miembro recibe sede, nacional y ministerios propios",async()=>{const[,,migration]=await agendaFiles();assert.match(migration,/audience_type='SITE'/);assert.match(migration,/audience_type in \('ALL_CRC','NATIONAL'\)/);assert.match(migration,/audience_type='MINISTRY'/)});
test("audiencia por rol se calcula acumulativamente",async()=>{const[,,migration]=await agendaFiles();assert.match(migration,/audience_type='ROLE'/);assert.match(migration,/ur\.role_id=ea\.role_id/);assert.match(migration,/or\(ea\.audience_type='SPECIFIC_USERS'/)});
test("evento de otra sede sin audiencia común queda oculto",async()=>{const[,,migration]=await agendaFiles();assert.match(migration,/p\.site_id=ea\.site_id/);assert.match(migration,/can_user_view_event/);assert.doesNotMatch(migration,/where e\.status.*or true/i)});
test("eventos específicos exigen el usuario autenticado destinatario",async()=>{const[,,migration]=await agendaFiles();assert.match(migration,/ea\.user_account_id=auth\.uid\(\)/);assert.match(migration,/SPECIFIC_USERS/)});
test("agenda excluye borradores cancelados archivados y expirados",async()=>{const[,,migration]=await agendaFiles();assert.match(migration,/status in \('SCHEDULED','IN_PROGRESS'\)/);assert.match(migration,/archived_at is null/);assert.match(migration,/coalesce\(e\.end_at,e\.start_at\)>=now\(\)/)});
test("evento vigente termina después de ahora aunque ya haya iniciado",async()=>{const[,,migration]=await agendaFiles();assert.match(migration,/coalesce\(e\.end_at,e\.start_at\)>=now\(\)/);assert.match(migration,/end_at/)});
test("detalle directo reutiliza la autorización del backend",async()=>{const[view,repository,migration]=await agendaFiles();assert.match(repository,/get_visible_event/);assert.match(migration,/case when public\.can_user_view_event\(e\.id\)/);assert.match(view,/role="dialog"/)});
test("consulta de agenda limita resultados y evita N más uno",async()=>{const[,repository,migration]=await agendaFiles();assert.match(repository,/get_my_upcoming_events/);assert.match(migration,/limit least\(greatest\(result_limit,1\),20\)/);assert.match(migration,/join public\.sites.*left join public\.ministries.*left join public\.people/s)});
test("Inicio muestra primero agenda y conserva paneles previos",async()=>{const[,,,,dashboard]=await agendaFiles();assert.ok(dashboard.indexOf("<AgendaCarousel/>")<dashboard.indexOf('className="metric-grid"'));assert.match(dashboard,/Notificaciones/);assert.match(dashboard,/ACCESOS RÁPIDOS/)});
test("carrusel es responsive táctil y accesible sin autoplay",async()=>{const[view,,,styles]=await agendaFiles();assert.match(view,/aria-label="Ver eventos anteriores"/);assert.match(view,/aria-label="Ver eventos siguientes"/);assert.match(view,/aria-label="Carrusel de próximos eventos"/);assert.doesNotMatch(view,/setInterval|autoplay/i);assert.match(styles,/scroll-snap-type:x mandatory/);assert.match(styles,/@media\(max-width:600px\).*grid-auto-columns:86%/s)});
test("cambios de evento y audiencia quedan auditados",async()=>{const[,,migration]=await agendaFiles();for(const action of["EVENT_CREATED","EVENT_UPDATED","EVENT_PUBLISHED","EVENT_CANCELLED","EVENT_AUDIENCE_UPDATED"])assert.match(migration,new RegExp(action))});
