"use client";

import {useEffect,useMemo,useState} from "react";
import {useAuth} from "@/features/auth/AuthProvider";
import {completeSession,createClassSession,createExternalStudent,createGroup,enrollPerson,loadDiscipleshipData,type Enrollment,type Group,type PersonOption,type Program,type Session,type Site} from "./repository";

const today=()=>new Date().toISOString().slice(0,10);const formatDate=(value:string)=>new Intl.DateTimeFormat("es-CO",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(`${value}T12:00:00`));
export function GroupsView({onOpenClass:_onOpenClass}:{onOpenClass:()=>void}){
 const{configured,session}=useAuth();const[sites,setSites]=useState<Site[]>([]);const[siteId,setSiteId]=useState("");const[people,setPeople]=useState<PersonOption[]>([]);const[programs,setPrograms]=useState<Program[]>([]);const[groups,setGroups]=useState<Group[]>([]);const[enrollments,setEnrollments]=useState<Enrollment[]>([]);const[sessions,setSessions]=useState<Session[]>([]);const[activeId,setActiveId]=useState("");const[tab,setTab]=useState<"students"|"sessions">("students");const[query,setQuery]=useState("");const[modal,setModal]=useState<"group"|"enroll"|"external"|"session"|"attendance"|null>(null);const[selectedSession,setSelectedSession]=useState<Session|null>(null);const[presentIds,setPresentIds]=useState<string[]>([]);const[notice,setNotice]=useState("");const[error,setError]=useState("");const[loading,setLoading]=useState(true);
 const[groupDraft,setGroupDraft]=useState({name:"",programId:"",teacherId:"",assistantId:"",startDate:today(),endDate:""});const[studentId,setStudentId]=useState("");const[external,setExternal]=useState({firstName:"",lastName:"",phone:"",email:""});const[sessionDraft,setSessionDraft]=useState({lessonId:"",teacherId:"",date:today(),time:"09:00"});
 const refresh=async(nextSite?:string)=>{setLoading(true);try{const data=await loadDiscipleshipData(nextSite);const resolved=nextSite&&data.sites.some(item=>item.id===nextSite)?nextSite:data.sites[0]?.id??"";setSites(data.sites);setSiteId(resolved);setPeople(data.people);setPrograms(data.programs);setGroups(data.groups);setEnrollments(data.enrollments);setSessions(data.sessions);setActiveId(current=>data.groups.some(item=>item.id===current)?current:data.groups[0]?.id??"");setError("")}catch{setError("No fue posible cargar los grupos autorizados de Supabase.")}finally{setLoading(false)}};
 useEffect(()=>{if(!configured||!session){setLoading(false);return}void refresh()},[configured,session]);
 const active=groups.find(item=>item.id===activeId);const site=sites.find(item=>item.id===siteId);const groupEnrollments=enrollments.filter(item=>item.groupId===activeId);const groupSessions=sessions.filter(item=>item.groupId===activeId);const visible=useMemo(()=>groupEnrollments.filter(item=>{const term=query.toLocaleLowerCase("es");return item.name.toLocaleLowerCase("es").includes(term)||item.crcCode.toLowerCase().includes(term)}),[groupEnrollments,query]);const availablePeople=people.filter(person=>!groupEnrollments.some(item=>item.personId===person.id));const activeProgram=programs.find(item=>item.id===active?.programId);const progress=groupEnrollments.length?Math.round(groupEnrollments.reduce((sum,item)=>sum+item.progress,0)/groupEnrollments.length):0;
 const fail=()=>setError("No fue posible guardar. Verifica datos, permisos y registros duplicados.");const done=async(text:string)=>{setModal(null);setNotice(text);setError("");await refresh(siteId)};
 const saveGroup=async(event:React.FormEvent)=>{event.preventDefault();if(!site)return;try{await createGroup(site,groupDraft);await done("Grupo creado y conectado al programa de Formación.")}catch{fail()}};
 const saveEnrollment=async()=>{if(!active||!studentId)return;try{await enrollPerson(active,studentId);await done("Alumno matriculado en el grupo.")}catch{fail()}};
 const saveExternal=async(event:React.FormEvent)=>{event.preventDefault();if(!site||!active)return;try{const id=await createExternalStudent(site,external);await enrollPerson(active,id);await done("Alumno externo registrado como visitante y matriculado.")}catch{fail()}};
 const saveSession=async(event:React.FormEvent)=>{event.preventDefault();if(!active)return;try{await createClassSession(active,sessionDraft);await done("Sesión programada con una lección de Formación.")}catch{fail()}};
 const openAttendance=(item:Session)=>{setSelectedSession(item);setPresentIds(item.presentIds);setModal("attendance")};const saveAttendance=async()=>{if(!active||!selectedSession)return;try{await completeSession(active,selectedSession,presentIds);await done("Clase finalizada; el avance de cada alumno fue recalculado.")}catch{fail()}};
 return <div className="content groups-content"><div className="module-heading"><div><span className="eyebrow">DISCIPULADO CONECTADO A FORMACIÓN</span><h1>Grupos de discipulado</h1><p>Crea grupos, elige maestros y alumnos, programa lecciones y mide el avance real.</p></div><button className="primary-button" onClick={()=>{setGroupDraft({name:"",programId:programs[0]?.id??"",teacherId:people[0]?.id??"",assistantId:"",startDate:today(),endDate:""});setModal("group")}} disabled={!programs.length||!people.length}>＋ Crear grupo</button></div>
  <div className="attendance-scope"><label><span>Sede responsable</span><select value={siteId} onChange={event=>void refresh(event.target.value)}>{sites.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><div><strong>{site?.name??"Sin sede"}</strong><span>Los alumnos externos se registran como visitantes de la sede responsable, no como congregantes.</span></div></div>{error&&<div className="form-error">{error}</div>}{notice&&<div className="form-success">✓ {notice}</div>}
  <div className="group-summary"><article><strong>{groups.filter(item=>item.status==="ACTIVE").length}</strong><span>grupos activos</span></article><article><strong>{enrollments.filter(item=>item.status==="ACTIVE").length}</strong><span>matrículas activas</span></article><article><strong>{sessions.filter(item=>item.status==="COMPLETED").length}</strong><span>clases completadas</span></article><div><b>{programs.length} programas de discipulado</b><span>Origen: módulo Formación</span></div></div>
  <section className="group-layout"><aside className="group-list"><div className="group-list-head"><strong>Grupos de la sede</strong><span>{groups.length}</span></div>{loading?<div className="group-empty"><span>Cargando…</span></div>:groups.map(group=><button key={group.id} className={group.id===activeId?"active":""} onClick={()=>{setActiveId(group.id);setNotice("")}}><span>{group.name.split(" ").slice(0,2).map(word=>word[0]).join("")}</span><div><strong>{group.name}</strong><small>{group.teacher} · {enrollments.filter(item=>item.groupId===group.id).length} alumnos</small></div><i className={group.status.toLowerCase()}>{group.status==="ACTIVE"?"Activo":"Planeado"}</i></button>)}{!loading&&!groups.length&&<div className="group-empty"><strong>Sin grupos reales</strong><span>Crea el primero usando un programa de Formación.</span></div>}</aside>
   <section className="group-detail">{active?<><header><div><span className="panel-kicker">{active.program}</span><h2>{active.name}</h2><p>{formatDate(active.startDate)} — {active.endDate?formatDate(active.endDate):"Sin fecha final"}</p></div><span className="access-state">{active.status}</span></header><div className="group-facts"><p><span>Maestro discipulador</span><strong>{active.teacher}</strong></p><p><span>Lecciones del programa</span><strong>{activeProgram?.lessonCount??0}</strong></p><p><span>Progreso promedio</span><strong>{progress}%</strong></p></div><nav className="group-tabs"><button className={tab==="students"?"active":""} onClick={()=>setTab("students")}>Alumnos <span>{groupEnrollments.length}</span></button><button className={tab==="sessions"?"active":""} onClick={()=>setTab("sessions")}>Clases <span>{groupSessions.length}</span></button></nav>
    {tab==="students"?<div className="enrollment-panel"><div className="group-tools"><label><span>⌕</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Buscar alumno o código CRC"/></label><button onClick={()=>{setStudentId(availablePeople[0]?.id??"");setModal("enroll")}}>＋ Matricular</button><button onClick={()=>setModal("external")}>＋ Alumno externo</button></div><div className="enrollment-list">{visible.map(item=><article key={item.id}><span className="enrollment-avatar">{item.name.split(" ").map(word=>word[0]).slice(0,2).join("")}</span><div><strong>{item.name}</strong><small>{item.crcCode} · {item.completed} de {item.total} lecciones completadas</small><i><b style={{width:`${item.progress}%`}}/></i></div><b>{item.progress}%</b></article>)}{!visible.length&&<div className="group-empty"><strong>Sin alumnos</strong><span>Matricula una persona existente o registra un alumno externo.</span></div>}</div></div>:<div className="session-panel"><div className="session-head"><div><strong>Lecciones impartidas</strong><span>Al finalizar una clase, la asistencia actualiza el avance.</span></div><button onClick={()=>{setSessionDraft({lessonId:activeProgram?.lessons[0]?.id??"",teacherId:active.teacherId,date:today(),time:"09:00"});setModal("session")}} disabled={!activeProgram?.lessons.length}>＋ Programar clase</button></div><div className="session-list">{groupSessions.map(item=><article key={item.id}><time><strong>{new Date(`${item.date}T12:00:00`).getDate()}</strong><span>{new Intl.DateTimeFormat("es-CO",{month:"short"}).format(new Date(`${item.date}T12:00:00`))}</span></time><div><strong>{item.lesson}</strong><small>{item.time.slice(0,5)} · Maestro: {item.teacher}</small></div><span className={item.status.toLowerCase()}>{item.status==="COMPLETED"?`${item.presentIds.length} presentes`:"Programada"}</span><button onClick={()=>openAttendance(item)}>{item.status==="COMPLETED"?"Ver/ajustar":"Registrar clase"} →</button></article>)}{!groupSessions.length&&<div className="group-empty"><strong>Sin clases programadas</strong><span>Selecciona una lección cargada en Formación.</span></div>}</div></div>}</>:<div className="group-empty"><strong>Selecciona un grupo</strong></div>}</section></section>
  {modal==="group"&&<Modal title="Crear grupo" close={()=>setModal(null)}><form onSubmit={saveGroup}><Fields><Field label="Nombre"><input required minLength={3} value={groupDraft.name} onChange={e=>setGroupDraft({...groupDraft,name:e.target.value})}/></Field><Field label="Programa de Formación"><select value={groupDraft.programId} onChange={e=>setGroupDraft({...groupDraft,programId:e.target.value})}>{programs.map(item=><option key={item.id} value={item.id}>{item.title} · {item.lessonCount} lecciones</option>)}</select></Field><Field label="Maestro discipulador"><select value={groupDraft.teacherId} onChange={e=>setGroupDraft({...groupDraft,teacherId:e.target.value})}>{people.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Asistente opcional"><select value={groupDraft.assistantId} onChange={e=>setGroupDraft({...groupDraft,assistantId:e.target.value})}><option value="">Sin asistente</option>{people.filter(item=>item.id!==groupDraft.teacherId).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Inicio"><input type="date" required value={groupDraft.startDate} onChange={e=>setGroupDraft({...groupDraft,startDate:e.target.value})}/></Field><Field label="Fin opcional"><input type="date" value={groupDraft.endDate} onChange={e=>setGroupDraft({...groupDraft,endDate:e.target.value})}/></Field></Fields><Actions/></form></Modal>}
  {modal==="enroll"&&<Modal title="Matricular persona" close={()=>setModal(null)}><Field label="Persona de la sede"><select value={studentId} onChange={e=>setStudentId(e.target.value)}>{availablePeople.map(item=><option key={item.id} value={item.id}>{item.name} · {item.crcCode}</option>)}</select></Field><div className="modal-actions"><button className="secondary-button" onClick={()=>setModal(null)}>Cancelar</button><button className="primary-button" onClick={()=>void saveEnrollment()} disabled={!studentId}>Matricular</button></div></Modal>}
  {modal==="external"&&<Modal title="Registrar alumno externo" close={()=>setModal(null)}><form onSubmit={saveExternal}><p className="privacy-note">Se creará como visitante vinculado administrativamente a {site?.name}; esto no significa que se congregue allí.</p><Fields><Field label="Nombre"><input required value={external.firstName} onChange={e=>setExternal({...external,firstName:e.target.value})}/></Field><Field label="Apellido"><input required value={external.lastName} onChange={e=>setExternal({...external,lastName:e.target.value})}/></Field><Field label="Celular"><input required minLength={7} value={external.phone} onChange={e=>setExternal({...external,phone:e.target.value})}/></Field><Field label="Correo opcional"><input type="email" value={external.email} onChange={e=>setExternal({...external,email:e.target.value})}/></Field></Fields><Actions label="Registrar y matricular"/></form></Modal>}
  {modal==="session"&&<Modal title="Programar clase" close={()=>setModal(null)}><form onSubmit={saveSession}><Fields><Field label="Lección de Formación"><select value={sessionDraft.lessonId} onChange={e=>setSessionDraft({...sessionDraft,lessonId:e.target.value})}>{activeProgram?.lessons.map(item=><option key={item.id} value={item.id}>{item.sortOrder}. {item.title}</option>)}</select></Field><Field label="Maestro que impartirá"><select value={sessionDraft.teacherId} onChange={e=>setSessionDraft({...sessionDraft,teacherId:e.target.value})}>{people.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Fecha"><input type="date" required value={sessionDraft.date} onChange={e=>setSessionDraft({...sessionDraft,date:e.target.value})}/></Field><Field label="Hora"><input type="time" required value={sessionDraft.time} onChange={e=>setSessionDraft({...sessionDraft,time:e.target.value})}/></Field></Fields><Actions label="Programar clase"/></form></Modal>}
  {modal==="attendance"&&selectedSession&&<Modal title={`Registrar clase · ${selectedSession.lesson}`} close={()=>setModal(null)}><div className="lesson-attendance"><p>Marca quienes recibieron esta lección. Al finalizar se recalcula el porcentaje individual.</p>{groupEnrollments.map(item=><label key={item.id}><input type="checkbox" checked={presentIds.includes(item.personId)} onChange={e=>setPresentIds(current=>e.target.checked?[...current,item.personId]:current.filter(id=>id!==item.personId))}/><span>{item.name}</span><small>{item.progress}% actual</small></label>)}</div><div className="modal-actions"><button className="secondary-button" onClick={()=>setModal(null)}>Cancelar</button><button className="primary-button" onClick={()=>void saveAttendance()}>Finalizar clase</button></div></Modal>}
 </div>;
}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="modal-layer"><button className="modal-scrim" onClick={close} aria-label="Cerrar"/><section className="person-modal"><div className="modal-head"><div><span className="eyebrow">DISCIPULADO</span><h2>{title}</h2></div><button onClick={close}>×</button></div>{children}</section></div>}
function Fields({children}:{children:React.ReactNode}){return <div className="form-grid">{children}</div>};function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="form-field"><span>{label}</span>{children}</label>};function Actions({label="Guardar grupo"}:{label?:string}){return <div className="modal-actions"><button className="primary-button" type="submit">{label}</button></div>}
