import {getSupabaseBrowserClient} from "@/lib/supabase/client";
export type IndividualAssignment={id:string;siteId:string;programId:string;program:string;discipleId:string;disciple:string;disciplerId:string;discipler:string;status:string;assignedAt:string;updatedAt:string;completed:number;total:number;progress:number;lastLessonAt:string|null;completedLessonIds:string[]};
export type IndividualDashboard={canAssign:boolean;canReassign:boolean;canRecord:boolean;assignments:IndividualAssignment[]};
export type IndividualCandidate={id:string;name:string;crc_code:string;site_name:string;phone_masked:string|null;document_masked:string|null};
export async function loadIndividualDashboard(siteId:string){const{data,error}=await getSupabaseBrowserClient().rpc("get_individual_discipleship_dashboard",{target_site_id:siteId});if(error)throw error;return data as IndividualDashboard}
export async function searchIndividualPeople(siteId:string,term:string,kind:"DISCIPLER"|"DISCIPLE"){const{data,error}=await getSupabaseBrowserClient().rpc("search_individual_discipleship_people",{target_site_id:siteId,search_term:term,candidate_kind:kind,result_limit:20});if(error)throw error;return(data??[])as IndividualCandidate[]}
export async function createIndividualAssignment(siteId:string,programId:string,discipleId:string,disciplerId:string,notes:string){const{data,error}=await getSupabaseBrowserClient().rpc("create_individual_discipleship",{target_site_id:siteId,target_program_id:programId,target_disciple_person_id:discipleId,target_discipler_person_id:disciplerId,given_notes:notes||null});if(error)throw error;return data as string}
export async function recordIndividualLesson(assignmentId:string,lessonId:string,draft:{date:string;time:string;modality:"IN_PERSON"|"VIRTUAL";notes:string}){const{data,error}=await getSupabaseBrowserClient().rpc("record_individual_discipleship_lesson",{target_assignment_id:assignmentId,target_lesson_id:lessonId,given_date:draft.date,given_time:draft.time||null,given_modality:draft.modality,given_notes:draft.notes||null});if(error)throw error;return data as string}
export async function reassignIndividual(assignmentId:string,disciplerId:string,reason:string){const{error}=await getSupabaseBrowserClient().rpc("reassign_individual_discipler",{target_assignment_id:assignmentId,new_discipler_person_id:disciplerId,given_reason:reason||null});if(error)throw error}
export async function swapIndividualParticipants(assignmentId:string){const{error}=await getSupabaseBrowserClient().rpc("swap_individual_discipleship_participants",{target_assignment_id:assignmentId});if(error)throw error}
