"use client";

import {useEffect,useMemo,useState} from "react";
import {useAuth} from "@/features/auth/AuthProvider";
import {createAttendanceEvent,loadAttendanceData,setPersonAttendance,type AttendanceEntry,type AttendanceEvent,type AttendancePerson,type AttendanceSite,type EventDraft} from "./repository";

const typeLabels:Record<string,string>={SERVICE:"Culto",DISCIPLESHIP:"Discipulado",COURSE:"Curso",PRAYER:"Oración",FAST:"Ayuno",MINISTRY_MEETING:"Reunión ministerial",CONFERENCE:"Conferencia",RETREAT:"Retiro",OTHER:"Otro"};
const statusLabels:Record<string,string>={DRAFT:"Borrador",SCHEDULED:"Programado",IN_PROGRESS:"En curso",COMPLETED:"Finalizado"};
const emptyDraft=():EventDraft=>({title:"",type:"SERVICE",startAt:new Date(Date.now()+3600000).toISOString().slice(0,16),endAt:"",location:"",status:"SCHEDULED"});
const age=(birthDate:string|null)=>birthDate?Math.floor((Date.now()-new Date(`${birthDate}T12:00:00`).getTime())/31557600000):null;
const ageLabel=(value:number|null)=>value===null?"Sin fecha":value<=5?"0–5":value<=11?"6–11":value<=17?"12–17":value<=26?"18–26":value<=59?"27–59":"60+";
const eventDate=(value:string)=>new Intl.DateTimeFormat("es-CO",{day:"2-digit",month:"short",hour:"numeric",minute:"2-digit"}).format(new Date(value));

export function AttendanceView(){
 const{configured,session}=useAuth();const[sites,setSites]=useState<AttendanceSite[]>([]);const[siteId,setSiteId]=useState("");const[people,setPeople]=useState<AttendancePerson[]>([]);const[events,setEvents]=useState<AttendanceEvent[]>([]);const[entries,setEntries]=useState<AttendanceEntry[]>([]);const[activeId,setActiveId]=useState("");const[query,setQuery]=useState("");const[loading,setLoading]=useState(true);const[busyId,setBusyId]=useState("");const[message,setMessage]=useState("");const[error,setError]=useState("");const[eventModal,setEventModal]=useState(false);const[draft,setDraft]=useState<EventDraft>(emptyDraft());
 const refresh=async(nextSiteId?:string)=>{setLoading(true);try{const data=await loadAttendanceData(nextSiteId);setSites(data.sites);const resolved=nextSiteId&&data.sites.some(item=>item.id===nextSiteId)?nextSiteId:data.sites[0]?.id??"";setSiteId(resolved);setPeople(data.people);setEvents(data.events);setEntries(data.entries);setActiveId(current=>data.events.some(item=>item.id===current)?current:data.events[0]?.id??"");setError("")}catch{setError("No fue posible cargar la asistencia autorizada para esta sede.")}finally{setLoading(false)}};
 useEffect(()=>{if(!configured||!session){setLoading(false);return}void refresh()},[configured,session]);
 const active=events.find(item=>item.id===activeId);const site=sites.find(item=>item.id===siteId);const eventEntries=useMemo(()=>entries.filter(item=>item.eventId===activeId),[entries,activeId]);const byPerson=useMemo(()=>new Map(eventEntries.map(item=>[item.personId,item])),[eventEntries]);
 const visible=useMemo(()=>people.filter(person=>{const term=query.trim().toLocaleLowerCase("es");return!term||person.name.toLocaleLowerCase("es").includes(term)||person.crcCode.toLowerCase().includes(term)}),[people,query]);
 const presentIds=useMemo(()=>new Set(eventEntries.filter(item=>item.status==="PRESENT"||item.status==="LATE").map(item=>item.personId)),[eventEntries]);const presentPeople=people.filter(person=>presentIds.has(person.id));const absent=eventEntries.filter(item=>item.status==="ABSENT"||item.status==="EXCUSED").length;const recurrent=presentPeople.filter(person=>person.status!=="VISITOR").length;const visitors=presentPeople.length-recurrent;const rate=people.length?Math.round(presentPeople.length/people.length*100):0;
 const ages=useMemo(()=>{const result=new Map<string,number>();for(const person of presentPeople){const label=ageLabel(age(person.birthDate));result.set(label,(result.get(label)??0)+1)}return["0–5","6–11","12–17","18–26","27–59","60+","Sin fecha"].map(label=>({label,count:result.get(label)??0})).filter(item=>item.count>0)},[presentPeople]);
 const toggle=async(person:AttendancePerson,present:boolean)=>{if(!active)return;setBusyId(person.id);setMessage("");try{const saved=await setPersonAttendance(active,person.id,byPerson.get(person.id),present);setEntries(current=>[...current.filter(item=>item.id!==saved.id),saved]);setMessage(`${person.name}: ${present?"asistencia registrada":"ausencia registrada"}.`);setError("")}catch{setError("No fue posible guardar el registro. Verifica que tu rol tenga permiso de asistencia en esta sede.")}finally{setBusyId("")}};
 const createEvent=async(event:React.FormEvent)=>{event.preventDefault();if(!site||draft.title.trim().length<2)return;try{const saved=await createAttendanceEvent(site,draft);setEvents(current=>[saved,...current]);setActiveId(saved.id);setEventModal(false);setDraft(emptyDraft());setMessage("Evento creado en la sede seleccionada.");setError("")}catch{setError("No fue posible crear el evento. Verifica fechas y permisos de la sede.")}};
 return <div className="content event-content"><div className="module-heading"><div><span className="eyebrow">EVENTOS Y CHECK-IN</span><h1>Asistencia por sede</h1><p>Registra cada persona una sola vez por evento y consulta indicadores reales.</p></div><button className="primary-button" onClick={()=>setEventModal(true)} disabled={!site}>＋ Crear evento</button></div>
  <div className="attendance-scope"><label><span>Sede</span><select value={siteId} onChange={event=>void refresh(event.target.value)}>{sites.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><div><strong>{site?.name??"Sin sede autorizada"}</strong><span>Eventos, personas e indicadores aislados por políticas RLS.</span></div></div>
  {error&&<div className="form-error">{error}</div>}{message&&<div className="form-success">✓ {message}</div>}
  <section className="attendance-kpis"><article><span>Personas de la sede</span><strong>{people.length}</strong><small>Registro activo</small></article><article><span>Presentes</span><strong>{presentPeople.length}</strong><small>{rate}% de la sede</small></article><article><span>Ausencias registradas</span><strong>{absent}</strong><small>{Math.max(people.length-presentPeople.length-absent,0)} pendientes</small></article><article><span>Recurrentes / visitantes</span><strong>{recurrent} / {visitors}</strong><small>En el evento seleccionado</small></article></section>
  <section className="event-layout"><aside className="event-list"><div className="event-list-head"><strong>Eventos de la sede</strong><span>{events.length}</span></div>{loading?<p className="attendance-empty">Cargando eventos…</p>:events.length===0?<p className="attendance-empty">Aún no hay eventos. Crea el primero para tomar asistencia.</p>:events.map(item=><button key={item.id} className={activeId===item.id?"active":""} onClick={()=>{setActiveId(item.id);setMessage("")}}><time><strong>{new Date(item.startAt).getDate()}</strong><small>{new Intl.DateTimeFormat("es-CO",{month:"short"}).format(new Date(item.startAt))}</small></time><div><strong>{item.title}</strong><small>{eventDate(item.startAt)} · {typeLabels[item.type]??item.type}</small></div><i className={`event-state ${item.status.toLowerCase()}`}>{statusLabels[item.status]??item.status}</i></button>)}</aside>
   <section className="checkin-panel">{active?<><div className="checkin-head"><div><span className="panel-kicker">{typeLabels[active.type]??active.type}</span><h2>{active.title}</h2><p>{eventDate(active.startAt)} · {active.location||site?.name}</p></div><div className="attendance-total"><strong>{presentPeople.length}</strong><span>presentes</span></div></div><div className="checkin-tools"><label><span>⌕</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Buscar nombre o código CRC" aria-label="Buscar persona para asistencia"/></label></div><div className="duplicate-note"><b>✓ Registro único</b><span>La base de datos impide duplicar una persona en el mismo evento.</span></div><div className="checkin-list">{visible.map(person=>{const entry=byPerson.get(person.id);const isPresent=entry?.status==="PRESENT"||entry?.status==="LATE";return <article key={person.id}><span className="checkin-avatar">{person.name.split(" ").map(part=>part[0]).slice(0,2).join("")}</span><div><strong>{person.name}</strong><small>{person.crcCode} · {entry?entry.status==="ABSENT"?"Ausente":"Registro manual":"Sin registrar"}</small></div><div className="attendance-actions"><button disabled={busyId===person.id} className={isPresent?"present":""} onClick={()=>void toggle(person,true)}>✓ Presente</button><button disabled={busyId===person.id} className={entry?.status==="ABSENT"?"absent":""} onClick={()=>void toggle(person,false)}>× Ausente</button></div></article>})}{!visible.length&&<p className="attendance-empty">No hay personas que coincidan con la búsqueda en esta sede.</p>}</div>{ages.length>0&&<div className="age-summary"><div><strong>Grupos de edad presentes</strong><span>Calculados desde la fecha de nacimiento</span></div>{ages.map(item=><p key={item.label}><span>{item.label}</span><b>{item.count}</b></p>)}</div>}</>:<div className="attendance-empty large"><strong>Selecciona o crea un evento</strong><span>Los indicadores se calcularán sólo con datos reales de la sede.</span></div>}</section></section>
  {eventModal&&<div className="modal-layer"><button className="modal-scrim" onClick={()=>setEventModal(false)} aria-label="Cerrar"/><section className="person-modal" role="dialog" aria-modal="true"><div className="modal-head"><div><span className="eyebrow">NUEVO EVENTO</span><h2>Crear evento en {site?.name}</h2></div><button onClick={()=>setEventModal(false)}>×</button></div><form onSubmit={createEvent}><div className="form-grid"><label className="form-field"><span>Nombre</span><input required minLength={2} value={draft.title} onChange={event=>setDraft({...draft,title:event.target.value})}/></label><label className="form-field"><span>Tipo</span><select value={draft.type} onChange={event=>setDraft({...draft,type:event.target.value})}>{Object.entries(typeLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="form-field"><span>Inicio</span><input required type="datetime-local" value={draft.startAt} onChange={event=>setDraft({...draft,startAt:event.target.value})}/></label><label className="form-field"><span>Fin opcional</span><input type="datetime-local" value={draft.endAt} onChange={event=>setDraft({...draft,endAt:event.target.value})}/></label><label className="form-field"><span>Lugar</span><input value={draft.location} onChange={event=>setDraft({...draft,location:event.target.value})}/></label><label className="form-field"><span>Estado</span><select value={draft.status} onChange={event=>setDraft({...draft,status:event.target.value})}>{["DRAFT","SCHEDULED","IN_PROGRESS","COMPLETED"].map(value=><option key={value} value={value}>{statusLabels[value]}</option>)}</select></label></div><div className="modal-actions"><button type="button" className="secondary-button" onClick={()=>setEventModal(false)}>Cancelar</button><button className="primary-button" type="submit">Guardar evento</button></div></form></section></div>}
 </div>;
}
