"use client";
import{useEffect,useState}from"react";
import type{PortalContext}from "@/features/access/repository";
import{loadPersonalCampus,type PersonalCampusData,type PersonalEvent}from"./repository";
type PersonalSection="home"|"profile"|"activities"|"discipleship"|"formation";
export function CampusView({context,onSignOut}:{context:PortalContext;onSignOut:()=>void}){const[section,setSection]=useState<PersonalSection>("home");const[data,setData]=useState<PersonalCampusData|null>(null);const[events,setEvents]=useState<PersonalEvent[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");useEffect(()=>{let active=true;loadPersonalCampus().then(result=>{if(active){setData(result.campus);setEvents(result.events);setError("")}}).catch(()=>{if(active)setError("No fue posible cargar tu información personal. Intenta nuevamente.")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);const assignments=data?.discipleships??[];const activeAssignment=assignments.find(item=>item.status!=="COMPLETED"&&item.status!=="CANCELLED")??assignments[0];const go=(next:PersonalSection)=>{setSection(next);window.scrollTo({top:0,behavior:"smooth"})};return <main className="personal-campus"><header><button className="personal-brand" onClick={()=>go("home")}><div className="brand-mark">CRC</div><div><small>CAMPUS CRC</small><strong>Mi CRC</strong></div></button><button onClick={onSignOut}>Salir</button></header><section>{section!=="home"&&<button className="personal-back" onClick={()=>go("home")}>← Volver a Inicio</button>}{loading?<div className="personal-loading">Cargando tu información…</div>:error?<div className="auth-error">{error}</div>:section==="home"?<><span className="eyebrow">EXPERIENCIA PERSONAL</span><h1>Bienvenido, {data?.profile.firstName||context.firstName||"a CRC"}</h1><p>Consulta tu información, actividades, formación y proceso de discipulado.</p><div className="personal-campus-grid"><PersonalCard title="Mi perfil" detail="Consulta tus datos personales" onClick={()=>go("profile")}/><PersonalCard title="Mi sede" detail={data?.profile.site||context.siteName||"Sede pendiente"} onClick={()=>go("profile")}/><PersonalCard title="Actividades" detail={events.length?`${events.length} actividades visibles para ti`:"No tienes actividades próximas"} onClick={()=>go("activities")}/><PersonalCard title="Mi discipulado" detail={activeAssignment?`${activeAssignment.program} · ${activeAssignment.progress}% de avance`:"Aún no tienes un discipulado asignado"} onClick={()=>go("discipleship")}/><PersonalCard title="Mi formación" detail={assignments.length?`${assignments.length} programa${assignments.length===1?"":"s"} asignado${assignments.length===1?"":"s"}`:"Sin programas asignados"} onClick={()=>go("formation")}/></div></>:section==="profile"?<ProfilePanel data={data}/>:section==="activities"?<ActivitiesPanel events={events}/>:section==="discipleship"?<DiscipleshipPanel assignments={assignments}/>:<FormationPanel assignments={assignments}/>}</section></main>}
function PersonalCard({title,detail,onClick}:{title:string;detail:string;onClick:()=>void}){return <button className="personal-card" onClick={onClick}><span>→</span><h2>{title}</h2><p>{detail}</p></button>}
function ProfilePanel({data}:{data:PersonalCampusData|null}){const p=data?.profile;return <div className="personal-detail"><span className="eyebrow">INFORMACIÓN PERSONAL</span><h1>Mi perfil</h1><div className="personal-profile-grid"><Info label="Nombre" value={`${p?.firstName??""} ${p?.lastName??""}`.trim()}/><Info label="Código CRC" value={p?.crcCode}/><Info label="Correo" value={p?.email}/><Info label="Celular" value={p?.phone}/><Info label="Ciudad" value={p?.city}/><Info label="Sede" value={p?.site}/></div><p className="personal-note">Esta información es privada y se muestra únicamente en tu sesión.</p></div>}
function ActivitiesPanel({events}:{events:PersonalEvent[]}){return <div className="personal-detail"><span className="eyebrow">AGENDA AUTORIZADA</span><h1>Mis actividades</h1><p>Eventos públicos, de tu sede o compartidos específicamente contigo.</p>{events.length?<div className="personal-list">{events.map(event=><article key={event.id}><time>{new Intl.DateTimeFormat("es-CO",{dateStyle:"medium",timeStyle:"short"}).format(new Date(event.start_at))}</time><h2>{event.title}</h2><p>{event.description||"Actividad CRC"}</p><small>{event.site_name}{event.location?` · ${event.location}`:""} · {event.modality==="VIRTUAL"?"Virtual":"Presencial"}</small></article>)}</div>:<Empty text="No tienes actividades próximas visibles."/>}</div>}
function DiscipleshipPanel({assignments}:{assignments:PersonalCampusData["discipleships"]}){return <div className="personal-detail"><span className="eyebrow">PROCESO PERSONAL</span><h1>Mi discipulado</h1>{assignments.length?assignments.map(item=><article className="personal-discipleship" key={item.id}><div className="personal-discipleship-head"><div><small>{item.site}</small><h2>{item.program}</h2><p>Discipulador: <strong>{item.discipler}</strong></p></div><strong>{item.progress}%</strong></div><div className="personal-progress" aria-label={`${item.progress}% completado`}><i style={{width:`${item.progress}%`}}/></div><p>{item.completed} de {item.total} lecciones completadas{item.lastLessonAt?` · Última clase: ${formatDate(item.lastLessonAt)}`:""}</p><div className="personal-lessons">{item.lessons.map((lesson,index)=><div key={lesson.id} className={lesson.completed?"done":""}><span>{lesson.completed?"✓":"○"}</span><div><strong>{index+1}. {lesson.title}</strong><small>{lesson.module}{lesson.deliveredOn?` · ${formatDate(lesson.deliveredOn)}`:""}{lesson.deliveredBy?` · ${lesson.deliveredBy}`:""}</small></div></div>)}</div></article>):<Empty text="Aún no tienes un discipulado asignado. Cuando el líder realice la asignación aparecerá aquí."/>}</div>}
function FormationPanel({assignments}:{assignments:PersonalCampusData["discipleships"]}){return <div className="personal-detail"><span className="eyebrow">FORMACIÓN ASIGNADA</span><h1>Mi formación</h1><p>Solo se muestran los programas vinculados a tu proceso personal.</p>{assignments.length?<div className="personal-list">{assignments.map(item=><article key={item.id}><small>{item.status.replaceAll("_"," ")}</small><h2>{item.program}</h2><p>{item.programDescription||"Programa de discipulado CRC"}</p><strong>{item.completed} de {item.total} lecciones · {item.progress}%</strong></article>)}</div>:<Empty text="Todavía no tienes programas de formación asignados."/>}</div>}
function Info({label,value}:{label:string;value:string|null|undefined}){return <div><small>{label}</small><strong>{value||"No informado"}</strong></div>}
function Empty({text}:{text:string}){return <div className="personal-empty"><strong>{text}</strong></div>}
const formatDate=(value:string)=>new Intl.DateTimeFormat("es-CO").format(new Date(`${value}T12:00:00`));
export function AccessStatusView({status,onPublic,onSignOut}:{status:PortalContext["status"];onPublic:()=>void;onSignOut:()=>void}){const copy=status==="PENDING_APPROVAL"?["Solicitud pendiente de aprobación","Tu registro ya se encuentra en nuestro sistema. Cuando tu sede autorice el acceso recibirás una notificación."]:status==="SUSPENDED"?["Acceso temporalmente suspendido","Comunícate con tu sede si necesitas información sobre el estado de tu acceso."]:status==="REJECTED"?["Solicitud no aprobada","Tu sede puede orientarte sobre la decisión y los pasos disponibles."]:["Acceso no disponible","Comunícate con tu sede para recibir orientación."];return <main className="access-status-page"><section><span className="registration-check">!</span><h1>{copy[0]}</h1><p>{copy[1]}</p><div><button className="primary-button" onClick={onPublic}>Continuar en el sitio público</button><button className="secondary-button" onClick={onSignOut}>Cambiar usuario</button></div></section></main>}
export function AccessDeniedView({onCampus}:{onCampus:()=>void}){return <main className="access-status-page"><section><span className="registration-check">!</span><h1>Acceso no autorizado</h1><p>Tu cuenta no tiene un permiso administrativo válido para consultar esta sección.</p><button className="primary-button" onClick={onCampus}>Volver a Mi CRC</button></section></main>}
