-- Sprint 9: sitio público, CMS, SEO y solicitudes protegidas.
create type public_content_status as enum ('DRAFT','PUBLISHED','ARCHIVED');
create type public_request_type as enum ('ORIENTATION','PRAYER','CONTACT');
create type public_request_status as enum ('NEW','IN_PROGRESS','CLOSED');

create table public_pages (id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id),site_id uuid references sites(id),slug text not null check(slug ~ '^/[a-z0-9/-]*$'),title text not null,seo_title text not null,seo_description text not null check(char_length(seo_description)<=160),status public_content_status not null default 'DRAFT',published_at timestamptz,created_by uuid references user_accounts(id),updated_by uuid references user_accounts(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,id));
create unique index public_pages_org_slug_unique on public_pages(organization_id,slug) where site_id is null;
create unique index public_pages_site_slug_unique on public_pages(organization_id,site_id,slug) where site_id is not null;
create table public_content_blocks (id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id),page_id uuid not null,block_type text not null,heading text,body text,settings jsonb not null default '{}',sort_order integer not null check(sort_order>=0),active boolean not null default true,created_by uuid references user_accounts(id),updated_by uuid references user_accounts(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),foreign key(organization_id,page_id) references public_pages(organization_id,id) on delete cascade,unique(page_id,sort_order));
create table public_contact_requests (id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id),site_id uuid references sites(id),request_type public_request_type not null,name text not null,phone text not null,email text,message text not null,consent_at timestamptz not null,status public_request_status not null default 'NEW',assigned_to uuid references user_accounts(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());

insert into permissions(code,name,description) values ('content.manage','Administrar contenido','Administrar contenido del sitio público'),('content.requests.read','Gestionar solicitudes públicas','Gestionar solicitudes públicas') on conflict(code) do nothing;
insert into role_permissions(role_id,permission_id) select r.id,p.id from roles r cross join permissions p where r.code in ('SUPER_ADMIN','NATIONAL_PASTOR','SITE_PASTOR','SITE_ADMIN') and p.code in ('content.manage','content.requests.read') on conflict do nothing;
alter table public_pages enable row level security; alter table public_content_blocks enable row level security; alter table public_contact_requests enable row level security;
create policy public_pages_visible on public_pages for select to anon,authenticated using(status='PUBLISHED' and published_at<=now());
create policy public_pages_manage on public_pages for all to authenticated using(current_user_has_permission('content.manage',organization_id,site_id)) with check(current_user_has_permission('content.manage',organization_id,site_id));
create policy public_blocks_visible on public_content_blocks for select to anon,authenticated using(exists(select 1 from public_pages p where p.id=page_id and p.status='PUBLISHED' and p.published_at<=now()));
create policy public_blocks_manage on public_content_blocks for all to authenticated using(exists(select 1 from public_pages p where p.id=page_id and current_user_has_permission('content.manage',p.organization_id,p.site_id))) with check(exists(select 1 from public_pages p where p.id=page_id and current_user_has_permission('content.manage',p.organization_id,p.site_id)));
create policy public_requests_staff on public_contact_requests for all to authenticated using(current_user_has_permission('content.requests.read',organization_id,site_id)) with check(current_user_has_permission('content.requests.read',organization_id,site_id));

create or replace function submit_public_contact(target_organization uuid,target_site uuid,kind public_request_type,visitor_name text,visitor_phone text,visitor_email text,visitor_message text,accepted_consent boolean) returns uuid language plpgsql security definer set search_path=public as $$ declare request_id uuid; begin if not accepted_consent or char_length(trim(visitor_name)) not between 2 and 120 or char_length(trim(visitor_phone)) not between 7 and 30 or char_length(trim(visitor_message)) not between 3 and 2000 then raise exception 'Solicitud inválida'; end if; if not exists(select 1 from organizations where id=target_organization) or (target_site is not null and not exists(select 1 from sites where id=target_site and organization_id=target_organization)) then raise exception 'Destino inválido'; end if; insert into public_contact_requests(organization_id,site_id,request_type,name,phone,email,message,consent_at) values(target_organization,target_site,kind,trim(visitor_name),trim(visitor_phone),nullif(trim(visitor_email),''),trim(visitor_message),now()) returning id into request_id; return request_id; end $$;
revoke all on function submit_public_contact(uuid,uuid,public_request_type,text,text,text,text,boolean) from public;
grant execute on function submit_public_contact(uuid,uuid,public_request_type,text,text,text,text,boolean) to anon,authenticated;
grant select on public_pages,public_content_blocks to anon,authenticated; grant insert,update,delete on public_pages,public_content_blocks to authenticated; grant select,update on public_contact_requests to authenticated;
create index public_pages_publish_idx on public_pages(status,published_at); create index public_requests_queue_idx on public_contact_requests(organization_id,site_id,status,created_at desc);
